version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: cat /sys/fs/cgroup/memory/memory.stat
      - run: cat /sys/fs/cgroup/cpuset/cpuset.cpus
      - run: cat /sys/fs/cgroup/cpu/cpu.shares
      - run: cat /sys/fs/cgroup/cpu/cpu.cfs_quota_us
      - run: cat /sys/fs/cgroup/cpu/cpuacct.usage_all
      - run: cat /sys/fs/cgroup/cpu/cpu.cfs_quota_us
      - run: cat /proc/1/cgroup
